import type { ThemeDefinition } from "./types";

export const THEME_STORAGE_KEY = "codepiper.theme";
export const DEFAULT_DARK_THEME_ID = "codepiper-dark";
export const DEFAULT_LIGHT_THEME_ID = "codepiper-light";

/**
 * Theme registry.
 *
 * Contributor workflow:
 * 1. Copy an existing object in `THEMES`.
 * 2. Set unique `id` + `label`.
 * 3. Fill `ui` with hex colors for app surfaces (these are converted to HSL CSS vars at runtime).
 * 4. Fill `terminal` with ANSI/xterm palette colors.
 *
 * No other UI code changes are required for a new preset.
 */
export const THEMES: readonly ThemeDefinition[] = [
  {
    id: "codepiper-dark",
    label: "CodePiper Dark",
    description: "Default dark theme with cyan accents.",
    mode: "dark",
    themeColor: "#0e1016",
    monacoTheme: "vs-dark",
    ui: {
      background: "#0e1016",
      foreground: "#f3f4f6",
      card: "#161b22",
      cardForeground: "#f3f4f6",
      popover: "#161b22",
      popoverForeground: "#f3f4f6",
      primary: "#06b6d4",
      primaryForeground: "#0e1016",
      secondary: "#222a35",
      secondaryForeground: "#f3f4f6",
      muted: "#222a35",
      mutedForeground: "#9ca3af",
      accent: "#243142",
      accentForeground: "#f3f4f6",
      destructive: "#dc2626",
      destructiveForeground: "#f8fafc",
      border: "#243142",
      input: "#243142",
      ring: "#06b6d4",
    },
    terminal: {
      background: "#0e1016",
      foreground: "#d4d4e0",
      cursor: "#67e8f9",
      cursorAccent: "#0e1016",
      selectionBackground: "#06b6d430",
      selectionForeground: "#d4d4e0",
      black: "#3a3a4a",
      red: "#f87171",
      green: "#4ade80",
      yellow: "#fbbf24",
      blue: "#60a5fa",
      magenta: "#c084fc",
      cyan: "#22d3ee",
      white: "#d4d4e0",
      brightBlack: "#5a5a6a",
      brightRed: "#fca5a5",
      brightGreen: "#86efac",
      brightYellow: "#fde68a",
      brightBlue: "#93c5fd",
      brightMagenta: "#d8b4fe",
      brightCyan: "#67e8f9",
      brightWhite: "#f0f0f8",
    },
  },
  {
    id: "codepiper-light",
    label: "CodePiper Light",
    description: "Editorial light theme with crisp contrast and sapphire accents.",
    mode: "light",
    themeColor: "#f5f7fb",
    monacoTheme: "vs",
    ui: {
      background: "#f5f7fb",
      foreground: "#121826",
      card: "#ffffff",
      cardForeground: "#121826",
      popover: "#ffffff",
      popoverForeground: "#121826",
      primary: "#1f5bd8",
      primaryForeground: "#f8fbff",
      secondary: "#e8edf6",
      secondaryForeground: "#172235",
      muted: "#eef2f8",
      mutedForeground: "#57627a",
      accent: "#dfe8f8",
      accentForeground: "#122038",
      destructive: "#c62828",
      destructiveForeground: "#ffffff",
      border: "#cad5e4",
      input: "#c4d0e0",
      ring: "#1f5bd8",
    },
    terminal: {
      background: "#f7faff",
      foreground: "#102035",
      cursor: "#1c2f4a",
      cursorAccent: "#ffffff",
      selectionBackground: "#1f5bd829",
      selectionForeground: "#102035",
      black: "#1e2a3f",
      red: "#c62828",
      green: "#2e7d32",
      yellow: "#93610d",
      blue: "#1e5bd7",
      magenta: "#7b2cbf",
      cyan: "#0e7490",
      white: "#d6e1f0",
      brightBlack: "#5a6a83",
      brightRed: "#ef4444",
      brightGreen: "#22a55a",
      brightYellow: "#b7791f",
      brightBlue: "#2563eb",
      brightMagenta: "#9333ea",
      brightCyan: "#0891b2",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    description: "Popular high-contrast purple theme.",
    mode: "dark",
    themeColor: "#282a36",
    monacoTheme: "vs-dark",
    ui: {
      background: "#282a36",
      foreground: "#f8f8f2",
      card: "#303442",
      cardForeground: "#f8f8f2",
      popover: "#303442",
      popoverForeground: "#f8f8f2",
      primary: "#bd93f9",
      primaryForeground: "#282a36",
      secondary: "#3b3f51",
      secondaryForeground: "#f8f8f2",
      muted: "#3b3f51",
      mutedForeground: "#bdc2d6",
      accent: "#44475a",
      accentForeground: "#f8f8f2",
      destructive: "#ff5555",
      destructiveForeground: "#ffffff",
      border: "#44475a",
      input: "#44475a",
      ring: "#8be9fd",
    },
    terminal: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a99",
      selectionForeground: "#f8f8f2",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "nord",
    label: "Nord",
    description: "Arctic blue palette from the Nord project.",
    mode: "dark",
    themeColor: "#2e3440",
    monacoTheme: "vs-dark",
    ui: {
      background: "#2e3440",
      foreground: "#d8dee9",
      card: "#3b4252",
      cardForeground: "#d8dee9",
      popover: "#3b4252",
      popoverForeground: "#d8dee9",
      primary: "#88c0d0",
      primaryForeground: "#2e3440",
      secondary: "#434c5e",
      secondaryForeground: "#d8dee9",
      muted: "#434c5e",
      mutedForeground: "#b7c0cf",
      accent: "#4c566a",
      accentForeground: "#eceff4",
      destructive: "#bf616a",
      destructiveForeground: "#eceff4",
      border: "#4c566a",
      input: "#4c566a",
      ring: "#81a1c1",
    },
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#2e3440",
      selectionBackground: "#4c566a99",
      selectionForeground: "#eceff4",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    description: "Retro contrast palette popular in Vim and terminal workflows.",
    mode: "dark",
    themeColor: "#282828",
    monacoTheme: "vs-dark",
    ui: {
      background: "#282828",
      foreground: "#ebdbb2",
      card: "#32302f",
      cardForeground: "#ebdbb2",
      popover: "#32302f",
      popoverForeground: "#ebdbb2",
      primary: "#fabd2f",
      primaryForeground: "#282828",
      secondary: "#3c3836",
      secondaryForeground: "#ebdbb2",
      muted: "#3c3836",
      mutedForeground: "#bdae93",
      accent: "#504945",
      accentForeground: "#fbf1c7",
      destructive: "#fb4934",
      destructiveForeground: "#fbf1c7",
      border: "#504945",
      input: "#504945",
      ring: "#d79921",
    },
    terminal: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#50494599",
      selectionForeground: "#fbf1c7",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    description: "Low-contrast classic palette by Ethan Schoonover.",
    mode: "dark",
    themeColor: "#002b36",
    monacoTheme: "vs-dark",
    ui: {
      background: "#002b36",
      foreground: "#839496",
      card: "#073642",
      cardForeground: "#93a1a1",
      popover: "#073642",
      popoverForeground: "#93a1a1",
      primary: "#268bd2",
      primaryForeground: "#002b36",
      secondary: "#0b3f4a",
      secondaryForeground: "#93a1a1",
      muted: "#0b3f4a",
      mutedForeground: "#657b83",
      accent: "#0f4754",
      accentForeground: "#eee8d5",
      destructive: "#dc322f",
      destructiveForeground: "#fdf6e3",
      border: "#0f4754",
      input: "#0f4754",
      ring: "#2aa198",
    },
    terminal: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      cursorAccent: "#002b36",
      selectionBackground: "#073642cc",
      selectionForeground: "#93a1a1",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#002b36",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
];

export const THEMES_BY_ID = new Map(THEMES.map((theme) => [theme.id, theme]));

export function getThemeById(themeId: string | null | undefined): ThemeDefinition | undefined {
  if (!themeId) return undefined;
  return THEMES_BY_ID.get(themeId);
}
